# Generated by Django 6.0.7 on 2026-07-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('iata', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(db_index=True, max_length=20)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_airport', models.CharField(blank=True, max_length=10, null=True)),
                ('departure_airport_name', models.CharField(blank=True, max_length=200, null=True)),
                ('departure_city', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_country', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_time_scheduled', models.DateTimeField(blank=True, null=True)),
                ('departure_time_actual', models.DateTimeField(blank=True, null=True)),
                ('departure_gate', models.CharField(blank=True, max_length=20, null=True)),
                ('departure_terminal', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_airport', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_airport_name', models.CharField(blank=True, max_length=200, null=True)),
                ('arrival_city', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_country', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_time_scheduled', models.DateTimeField(blank=True, null=True)),
                ('arrival_time_actual', models.DateTimeField(blank=True, null=True)),
                ('arrival_gate', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_terminal', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
